dependencies {
    localRuntime "maven.modrinth:bclib-neoforge:21.0.26-neoforge"
    localRuntime "maven.modrinth:wunderlib-neoforge:21.0.10-neoforge"
    localRuntime "maven.modrinth:oh-the-trees-youll-grow:${minecraft_version}-5.3.2-NeoForge"

    implementation "maven.modrinth:worldweaver-neoforge:${wover_version}-neoforge"
    implementation "maven.modrinth:nether-descent:${descent_version}-NeoForge-mc${minecraft_version}"
}

group = mod_group_id
version = "${minecraft_version}-${mod_version}"
jar.archiveFileName = "${mod_id}-${minecraft_version}-${mod_version}.jar"
base.archivesName = mod_id

neoForge {
    version = neoforge_version

    parchment {
        mappingsVersion = parchment_version
        minecraftVersion = minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version           : minecraft_version,
            neoforge_version            : neoforge_version,
            loader_version_range        : loader_version_range,

            wover_version               : wover_version,
            descent_version             : descent_version,

            mod_id                      : mod_id,
            mod_name                    : mod_name,
            repo_name                   : repo_name,
            mod_license                 : mod_license,
            mod_version                 : mod_version,
            mod_author                  : mod_author,
            mod_description             : mod_description,
            mod_credits                 : mod_credits
    ]

    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}