## Mod Properties
mod_id=netherdescent_wover
mod_name=Nether Descent Wover Compat
repo_name=NetherDescent_Wover
mod_license=MIT
mod_version=1.0.0
mod_author=RedCraft86
mod_group_id=com.redcraft86.netherdescent_wover
mod_description=A compatibility mod that registers Nether Descent's biomes using World Weaver: New Dawn's API.
mod_credits=Reijin2312 (World Weaver: New Dawn), Potion Studios (Nether Descent)

## Dependencies
wover_version=21.0.25
descent_version=1.0.8